pipeline:
  build:
    image: node:12
    pull: true
    when:
      event: push
      branch:
        include: [master]
    commands:
      - yarn
      - PORT=3060 yarn generate
  deploy:
    image: drillster/drone-rsync
    hosts: [hanneko.no]
    key: ${RSYNC_KEY}
    secrets: [rsync_key]
    target: /home/niklasmh/hanneko-cv
    when:
      status: success
      event: [push, tag]
      branch: master
    script:
      - systemctl restart hanneko-cv
      - sleep 3
      - node generate-pdf.js
      - mv cv_hanneko_*.pdf /home/niklasmh/hanneko/build
