version: '3'

services:
  server:
    image: node:12
    command: yarn start
    restart: always
    ports:
      - ${DOCKER_PORT:-3010}:3000
    volumes:
      - .:/srv/hanne:rw
    working_dir: /srv/hanne
  generate-pdf:
    image: alekzonder/puppeteer
    command: node generate-pdf
    volumes:
      - .:/app
