version: '3'

services:
  server:
    image: node:12
    command: yarn start
    restart: always
    ports:
      - ${DOCKER_PORT}:3000
    volumes:
      - .:/srv/hanne:rw
    working_dir: /srv/hanne
